# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: .next/standalone

jobs:
# Please do not rename this job
  build-project:
    name: build SCWebsite
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        run: npm ci

      - name: Run script
        env:
          RESEND_API_KEY: re_hBKaEoL5_FALM2ZqidmkxfF1MmPb4W16L
          SITE_URL: ${{ inputs.site-url }}
        run: npm run build

      - name: Prepare standalone deployment
        run: |
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static
          echo '{"scripts":{"start":"node server.js"}}' > .next/standalone/package.json

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 9870e816-7152-4c98-bdb2-b8095abeb74c
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/SCWebsite/config.yaml
          action: upload
